# Generated by Django 3.1.4 on 2020-12-03 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
